spring:
  cloud:
    config:
      label: dev
      discovery:
        enabled: true
  config:
    import: "configserver:"

eureka:
  client:
    service-url:
      defaultZone: "http://awl-cloud-eureka:8080/eureka/"